import { Home, Info, ListOrdered, ShoppingBag, Store } from "lucide-react"

export interface NavItem {
  label: string
  href: string
  icon: React.ComponentType<{ className?: string }>
  mobileBar?: boolean
}

export const publicNavItems: NavItem[] = [
  { label: "Home", href: "/", icon: Home, mobileBar: true },
  { label: "Restaurants", href: "/restaurants", icon: Store, mobileBar: true },
  { label: "About Us", href: "/about-us", icon: Info },
]

export const protectedNavItems: NavItem[] = [
  { label: "Orders", href: "/orders", icon: ListOrdered },
  { label: "Cart", href: "/cart", icon: ShoppingBag, mobileBar: true },
]

export const restaurants = [
  {
    id: "1",
    name: "The Hub Hotel Restaurant",
    slug: "the-hub-hotel-restaurant",
    image: "/images/res-1.jpg",
    address: "Wilberforce, Freetown, Sierra Leone",
    location: "Wilberforce",
    phone: "+232 76 123456",
    cuisine: ["African", "International"],
    description:
      "A modern restaurant serving local Sierra Leonean dishes and international meals.",
    open_time: "07:00",
    close_time: "22:00",
    rating: 4.6,
    total_reviews: 245,
    delivery_time_min: 25,
    delivery_time_max: 35,
    delivery_fee: 5000,
    is_open: true,
    featured: true,
  },

  {
    id: "2",
    name: "Bai Bureh's Beach Restaurant",
    slug: "bai-burehs-beach-restaurant",
    image: "/images/res-2.jpg",
    address: "Lumley Beach Road, Freetown, Sierra Leone",
    location: "Lumley",
    phone: "+232 77 234567",
    cuisine: ["Seafood", "African"],
    description:
      "Beachside dining with fresh seafood and traditional Sierra Leone meals.",
    open_time: "10:00",
    close_time: "23:00",
    rating: 4.5,
    total_reviews: 189,
    delivery_time_min: 30,
    delivery_time_max: 45,
    delivery_fee: 6000,
    is_open: true,
    featured: true,
  },

  {
    id: "3",
    name: "Crown Bakery & Restaurant",
    slug: "crown-bakery-restaurant",
    image: "/images/res-3.jpg",
    address: "Wilberforce Street, Freetown, Sierra Leone",
    location: "Wilberforce",
    phone: "+232 78 345678",
    cuisine: ["Bakery", "Breakfast"],
    description: "Fresh pastries, breakfast meals and local favourites.",
    open_time: "06:30",
    close_time: "21:00",
    rating: 4.4,
    total_reviews: 152,
    delivery_time_min: 20,
    delivery_time_max: 30,
    delivery_fee: 4000,
    is_open: true,
    featured: false,
  },

  {
    id: "4",
    name: "Toma Restaurant",
    slug: "toma-restaurant",
    image: "/images/res-4.jpg",
    address: "Aberdeen, Freetown, Sierra Leone",
    location: "Aberdeen",
    phone: "+232 79 456789",
    cuisine: ["African", "Grill"],
    description:
      "Popular restaurant offering grilled meals and traditional dishes.",
    open_time: "09:00",
    close_time: "22:30",
    rating: 4.3,
    total_reviews: 134,
    delivery_time_min: 25,
    delivery_time_max: 40,
    delivery_fee: 5000,
    is_open: true,
    featured: false,
  },

  {
    id: "5",
    name: "Papaya Restaurant",
    slug: "papaya-restaurant",
    image: "/images/res-5.jpg",
    address: "Lumley, Freetown, Sierra Leone",
    location: "Lumley",
    phone: "+232 76 567890",
    cuisine: ["International", "Fast Food"],
    description: "Casual dining with burgers, rice meals and drinks.",
    open_time: "08:00",
    close_time: "23:00",
    rating: 4.2,
    total_reviews: 201,
    delivery_time_min: 20,
    delivery_time_max: 35,
    delivery_fee: 5000,
    is_open: true,
    featured: false,
  },

  {
    id: "6",
    name: "Bistro Restaurant",
    slug: "bistro-restaurant",
    image: "/images/res-6.jpg",
    address: "Hill Station, Freetown, Sierra Leone",
    location: "Hill Station",
    phone: "+232 77 678901",
    cuisine: ["European", "International"],
    description: "A quiet restaurant offering premium meals.",
    open_time: "11:00",
    close_time: "22:00",
    rating: 4.7,
    total_reviews: 98,
    delivery_time_min: 35,
    delivery_time_max: 50,
    delivery_fee: 7000,
    is_open: true,
    featured: true,
  },

  {
    id: "7",
    name: "Mamba Point Lagoonda Restaurant",
    slug: "mamba-point-lagoonda",
    image: "/images/res-7.jpg",
    address: "Aberdeen, Freetown, Sierra Leone",
    location: "Aberdeen",
    phone: "+232 78 789012",
    cuisine: ["Seafood", "African"],
    description: "Ocean view restaurant with seafood and local cuisine.",
    open_time: "08:00",
    close_time: "00:00",
    rating: 4.8,
    total_reviews: 320,
    delivery_time_min: 30,
    delivery_time_max: 45,
    delivery_fee: 8000,
    is_open: true,
    featured: true,
  },

  {
    id: "8",
    name: "Sierra Palms Restaurant",
    slug: "sierra-palms-restaurant",
    image: "/images/res-8.jpg",
    address: "Lumley Beach, Freetown, Sierra Leone",
    location: "Lumley",
    phone: "+232 79 890123",
    cuisine: ["African", "Seafood"],
    description: "Relaxed dining near the beach.",
    open_time: "07:30",
    close_time: "22:30",
    rating: 4.5,
    total_reviews: 176,
    delivery_time_min: 25,
    delivery_time_max: 40,
    delivery_fee: 6000,
    is_open: true,
    featured: false,
  },

  {
    id: "9",
    name: "City Garden Restaurant",
    slug: "city-garden-restaurant",
    image: "/images/res-9.jpg",
    address: "Congo Cross, Freetown, Sierra Leone",
    location: "Congo Cross",
    phone: "+232 76 901234",
    cuisine: ["African", "Fast Food"],
    description: "Affordable meals for families and groups.",
    open_time: "09:00",
    close_time: "21:30",
    rating: 4.1,
    total_reviews: 87,
    delivery_time_min: 20,
    delivery_time_max: 30,
    delivery_fee: 4000,
    is_open: true,
    featured: false,
  },

  {
    id: "10",
    name: "Ocean View Restaurant",
    slug: "ocean-view-restaurant",
    image: "/images/res-10.jpg",
    address: "Cape Road, Freetown, Sierra Leone",
    location: "Cape Road",
    phone: "+232 77 012345",
    cuisine: ["Seafood", "International"],
    description: "Beautiful ocean view dining experience.",
    open_time: "10:00",
    close_time: "23:00",
    rating: 4.6,
    total_reviews: 210,
    delivery_time_min: 30,
    delivery_time_max: 45,
    delivery_fee: 7000,
    is_open: true,
    featured: true,
  },
]

export const menuItems = [
  {
    id: "1-1",
    restaurant_id: "1",
    name: "Jollof Rice",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26",
    category: "lunch",
    price: 50000,
    discount_price: null,
    ingredients: ["Rice", "Tomatoes", "Chicken", "Onions", "Spices"],
    prep_time_min: 25,
    rating: 4.8,
    reviews_count: 54,
    stock_quantity: 20,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "1-2",
    restaurant_id: "1",
    name: "Pepper Chicken",
    image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
    category: "breakfast",
    price: 60000,
    discount_price: 55000,
    ingredients: ["Chicken", "Pepper", "Garlic", "Onions", "Herbs"],
    prep_time_min: 30,
    rating: 4.7,
    reviews_count: 38,
    stock_quantity: 15,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "2-1",
    restaurant_id: "1",
    name: "Grilled Fish",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
    category: "snacks",
    price: 75000,
    discount_price: null,
    ingredients: ["Fresh Fish", "Lemon", "Pepper", "Spices"],
    prep_time_min: 35,
    rating: 4.9,
    reviews_count: 70,
    stock_quantity: 10,
    is_sold_out: true,
    available: true,
    popular: true,
  },

  {
    id: "2-2",
    restaurant_id: "1",
    name: "Seafood Rice",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    category: "dinner",
    price: 65000,
    discount_price: null,
    ingredients: ["Rice", "Shrimp", "Fish", "Vegetables"],
    prep_time_min: 30,
    rating: 4.6,
    reviews_count: 42,
    stock_quantity: 12,
    is_sold_out: false,
    available: true,
    popular: false,
  },

  {
    id: "3-1",
    restaurant_id: "3",
    name: "Meat Pie",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff",
    category: "snacks",
    price: 10000,
    discount_price: null,
    ingredients: ["Flour", "Beef", "Butter", "Spices"],
    prep_time_min: 15,
    rating: 4.5,
    reviews_count: 25,
    stock_quantity: 50,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "4-1",
    restaurant_id: "4",
    name: "BBQ Chicken",
    image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2",
    category: "dinner",
    price: 70000,
    discount_price: null,
    ingredients: ["Chicken", "BBQ Sauce", "Spices"],
    prep_time_min: 35,
    rating: 4.7,
    reviews_count: 44,
    stock_quantity: 8,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "5-1",
    restaurant_id: "1",
    name: "Chicken Burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    category: "drinks",
    price: 45000,
    discount_price: 40000,
    ingredients: ["Cheese", "Tomatoes", "Chicken"],
    prep_time_min: 20,
    rating: 4.4,
    reviews_count: 31,
    stock_quantity: 25,
    is_sold_out: false,
    available: true,
    popular: false,
  },

  {
    id: "6-1",
    restaurant_id: "1",
    name: "Pasta Alfredo",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601",
    category: "drinks",
    price: 80000,
    discount_price: null,
    ingredients: ["Pasta", "Cream", "Cheese", "Chicken"],
    prep_time_min: 30,
    rating: 4.8,
    reviews_count: 60,
    stock_quantity: 14,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "7-1",
    restaurant_id: "1",
    name: "Lobster Special",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    category: "breakfast",
    price: 120000,
    discount_price: null,
    ingredients: ["Lobster", "Butter", "Garlic", "Spices"],
    prep_time_min: 45,
    rating: 4.9,
    reviews_count: 80,
    stock_quantity: 5,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "8-1",
    restaurant_id: "1",
    name: "Cassava Leaf",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    category: "breakfast",
    price: 40000,
    discount_price: null,
    ingredients: ["Cassava Leaf", "Rice", "Meat", "Palm Oil"],
    prep_time_min: 40,
    rating: 4.8,
    reviews_count: 52,
    stock_quantity: 20,
    is_sold_out: false,
    available: true,
    popular: true,
  },

  {
    id: "9-1",
    restaurant_id: "1",
    name: "Fried Rice",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b",
    category: "lunch",
    price: 45000,
    discount_price: null,
    ingredients: ["Rice", "Vegetables", "Egg", "Chicken"],
    prep_time_min: 25,
    rating: 4.5,
    reviews_count: 36,
    stock_quantity: 30,
    is_sold_out: false,
    available: true,
    popular: false,
  },

  {
    id: "10-1",
    restaurant_id: "1",
    name: "Grilled Seafood Platter",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de",
    category: "dinner",
    price: 100000,
    discount_price: null,
    ingredients: ["Fish", "Shrimp", "Calamari", "Spices"],
    prep_time_min: 45,
    rating: 4.9,
    reviews_count: 90,
    stock_quantity: 7,
    is_sold_out: false,
    available: true,
    popular: true,
  },
]
